services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_REEF_RPC_URL: /api/reef-rpc
      VITE_REEF_EXPLORER_API_URL: http://reef-explorer-ipwkoo-6aeed5-72-60-35-83.sslip.io/
      VITE_REEF_EXPLORER_URL: https://reefscan.com
    expose:
      - "43173"
