services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_REEF_RPC_URL: /api/reef-rpc
      VITE_REEF_RPC_TARGET: https://eth.reef-node-reefdevcluster-b0be3e-72-60-35-83.nip.io/
      VITE_REEF_EXPLORER_API_URL: https://explorer-backend-zw2mmk-102f32-72-60-35-83.nip.io
      VITE_REEF_EXPLORER_URL: https://explorer-frontend-ibcy8d-1204c4-72-60-35-83.nip.io
    expose:
      - "43173"
